### ISSUE TITLE
Package Name

### ISSUE THREAD

**Issue by idkjs** [matthewmueller/graph.ql#27]
You should consider changing the name of this amazing project. It is nearly impossible to find in any kind of search on net or github. Maybe fastql or mattql or eminemql or something. graph.ql gets searched same as graphql in any context. 

Keep up the good work!

**Comment by matthewmueller** [comment]
thanks for the feedback! i'm open to ideas here, though i do sort of like the elegance of the name, since it's a graphql language.

**Comment by valoricDe** [comment]
What about BabelQLizer or TheBabelOfGraphQL xD because babel also converts new cool javascript into old lengthy javascritpt.

**Comment by idkjs** [comment]
@matthewmueller elegant but completely unfindable, brother. Art over convention! I think you could get some legs with this if people new what it was. Was kinda shocked it didnt have more activity around it given its simplicity. But then if you dont care for the attention....

Either way, good work.

**Comment by igl** [comment]
This was my first choice after toying with the reference implementation and it made things very easy.

I like `graspQL` because of it's simplicity.
